name: CI
on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
      
      - run: npm install
      - run: npm run build

      - name: Create ory verify file
        run: |
          mkdir -p build/.well-known
          echo "ory-verify=orynth-ec94066d75ee4b34b33e3a9a1e5cac18" > build/.well-known/ory-verify.txt

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          commit_message: ${{ github.event.head_commit.message }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          force_orphan: true